name: NodeJS

on: push

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-environment

      - name: Run build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-environment

      - name: Run eslint
        run: npm run lint

      - name: Run prettier
        run: npm run format:check

      - name: Run tests
        run: npm run test

      - name: Check translations
        run: npm run i18n:extract && npm run i18n:check
